In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.1'

In [4]:
x = [3, 9, 6, 7, 12, 45, 18]
ser = pd.Series(x)
ser

0     3
1     9
2     6
3     7
4    12
5    45
6    18
dtype: int64

In [5]:
ser[0]

np.int64(3)

In [6]:
x = [3, 9, 6, 7, 12, 45, 18]
ser = pd.Series(x,index = ['A', 'B', 'C', 'D', 'E', 'F', 'G'])
ser

A     3
B     9
C     6
D     7
E    12
F    45
G    18
dtype: int64

In [7]:
df = pd.read_csv("data.csv")
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [10]:
df = df.fillna(130)
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112     130.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           130    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132     130.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [11]:
df = pd.read_csv("data.csv")
df
df.Duration.replace(450,40)

0     60
1     60
2     60
3     45
4     45
5     60
6     60
7     40
8     30
9     60
10    60
11    60
12    60
13    60
14    60
15    60
16    60
17    60
18    45
19    60
20    45
21    60
22    45
23    60
24    45
25    60
26    60
27    60
28    60
29    60
30    60
31    60
Name: Duration, dtype: int64

In [12]:
new_df = df["Calories"].fillna(130)
new_df

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18    130.0
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28    130.0
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [13]:
df = pd.read_csv("data.csv")
new_df = df.dropna()
new_df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [15]:
new_df = df["Calories"].dropna()
new_df

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [17]:
df_cal = df["Calories"]
df_cal

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18      NaN
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28      NaN
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [19]:
df_mean = df["Calories"].mean()
df["Calories"].fillna(df_mean)

0     409.10
1     479.00
2     340.00
3     282.40
4     406.00
5     300.00
6     374.00
7     253.30
8     195.10
9     269.00
10    329.30
11    250.70
12    250.70
13    345.30
14    379.30
15    275.00
16    215.20
17    300.00
18    304.68
19    323.00
20    243.00
21    364.20
22    282.00
23    300.00
24    246.00
25    334.50
26    250.00
27    241.00
28    304.68
29    280.00
30    380.30
31    243.00
Name: Calories, dtype: float64

In [20]:
df_median = df["Calories"].median()
df["Calories"].fillna(df_median)

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18    291.2
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28    291.2
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [21]:
df_mode = df["Calories"].mode()[0]
df["Calories"].fillna(df_mode)

0     409.1
1     479.0
2     340.0
3     282.4
4     406.0
5     300.0
6     374.0
7     253.3
8     195.1
9     269.0
10    329.3
11    250.7
12    250.7
13    345.3
14    379.3
15    275.0
16    215.2
17    300.0
18    300.0
19    323.0
20    243.0
21    364.2
22    282.0
23    300.0
24    246.0
25    334.5
26    250.0
27    241.0
28    300.0
29    280.0
30    380.3
31    243.0
Name: Calories, dtype: float64

In [22]:
df["Date"]

0     '2020/12/01'
1     '2020/12/02'
2     '2020/12/03'
3     '2020/12/04'
4     '2020/12/05'
5     '2020/12/06'
6     '2020/12/07'
7     '2020/12/08'
8     '2020/12/09'
9     '2020/12/10'
10    '2020/12/11'
11    '2020/12/12'
12    '2020/12/12'
13    '2020/12/13'
14    '2020/12/14'
15    '2020/12/15'
16    '2020/12/16'
17    '2020/12/17'
18    '2020/12/18'
19    '2020/12/19'
20    '2020/12/20'
21    '2020/12/21'
22             NaN
23    '2020/12/23'
24    '2020/12/24'
25    '2020/12/25'
26        20201226
27    '2020/12/27'
28    '2020/12/28'
29    '2020/12/29'
30    '2020/12/30'
31    '2020/12/31'
Name: Date, dtype: str

In [24]:
df["Date"] = pd.to_datetime(df['Date'], format = 'mixed')
df["Date"]

0    2020-12-01
1    2020-12-02
2    2020-12-03
3    2020-12-04
4    2020-12-05
5    2020-12-06
6    2020-12-07
7    2020-12-08
8    2020-12-09
9    2020-12-10
10   2020-12-11
11   2020-12-12
12   2020-12-12
13   2020-12-13
14   2020-12-14
15   2020-12-15
16   2020-12-16
17   2020-12-17
18   2020-12-18
19   2020-12-19
20   2020-12-20
21   2020-12-21
22          NaT
23   2020-12-23
24   2020-12-24
25   2020-12-25
26   2020-12-26
27   2020-12-27
28   2020-12-28
29   2020-12-29
30   2020-12-30
31   2020-12-31
Name: Date, dtype: datetime64[us]

In [25]:
df["Duration"]

0      60
1      60
2      60
3      45
4      45
5      60
6      60
7     450
8      30
9      60
10     60
11     60
12     60
13     60
14     60
15     60
16     60
17     60
18     45
19     60
20     45
21     60
22     45
23     60
24     45
25     60
26     60
27     60
28     60
29     60
30     60
31     60
Name: Duration, dtype: int64

In [26]:
df.loc[7,"Duration"] = 45
df["Duration"]

0     60
1     60
2     60
3     45
4     45
5     60
6     60
7     45
8     30
9     60
10    60
11    60
12    60
13    60
14    60
15    60
16    60
17    60
18    45
19    60
20    45
21    60
22    45
23    60
24    45
25    60
26    60
27    60
28    60
29    60
30    60
31    60
Name: Duration, dtype: int64

In [27]:
for x in df.index:
    if df.loc[x,"Duration"] > 60:
        df.loc[x,"Duration"] = 60
df["Duration"]

0     60
1     60
2     60
3     45
4     45
5     60
6     60
7     45
8     30
9     60
10    60
11    60
12    60
13    60
14    60
15    60
16    60
17    60
18    45
19    60
20    45
21    60
22    45
23    60
24    45
25    60
26    60
27    60
28    60
29    60
30    60
31    60
Name: Duration, dtype: int64

In [28]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [30]:
df.drop_duplicates()

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [31]:
df.corr()

          Duration      Date     Pulse  Maxpulse  Calories
Duration  1.000000  0.203538 -0.066974 -0.258764  0.335571
Date      0.203538  1.000000 -0.360587 -0.502902 -0.352105
Pulse    -0.066974 -0.360587  1.000000  0.276583  0.513186
Maxpulse -0.258764 -0.502902  0.276583  1.000000  0.357460
Calories  0.335571 -0.352105  0.513186  0.357460  1.000000

In [32]:
df

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [33]:
df.iloc[0]

Duration                     60
Date        2020-12-01 00:00:00
Pulse                       110
Maxpulse                    130
Calories                  409.1
Name: 0, dtype: object

In [34]:
df.iloc[[1,3,5],1]

1   2020-12-02
3   2020-12-04
5   2020-12-06
Name: Date, dtype: datetime64[us]

In [37]:
df.loc[0,"Calories"]

np.float64(409.1)

In [38]:
df.loc[df.Duration == 60]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [39]:
df.loc[(df.Duration == 60) & (df.Pulse == 110)]

   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
6        60 2020-12-07    110       136     374.0

In [41]:
df.loc[(df.Duration == 60) | (df.Pulse == 110)]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [42]:
df.loc[df.Pulse.isin([100,50])]

    Duration       Date  Pulse  Maxpulse  Calories
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
17        60 2020-12-17    100       120     300.0
22        45        NaT    100       119     282.0
26        60 2020-12-26    100       120     250.0
29        60 2020-12-29    100       132     280.0

In [43]:
df.loc[df.Calories.notnull()]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [44]:
df[pd.isnull(df.Calories)]

    Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112       NaN
28        60 2020-12-28    103       132       NaN

In [47]:
df.describe()

,Duration,Date,Pulse,Maxpulse,Calories
count,32.000000,31,32.000000,32.000000,30.000000
mean,55.781250,2020-12-15 16:15:29.032258,103.500000,128.500000,304.680000
min,30.000000,2020-12-01 00:00:00,90.000000,101.000000,195.100000
25%,56.250000,2020-12-08 12:00:00,100.000000,120.000000,250.700000
50%,60.000000,2020-12-15 00:00:00,102.500000,127.500000,291.200000
75%,60.000000,2020-12-23 12:00:00,106.500000,132.250000,343.975000
max,60.000000,2020-12-31 00:00:00,130.000000,175.000000,479.000000
std,7.840072,NaN,7.832933,12.998759,66.003779

In [48]:
df.Pulse.unique()

array([110, 117, 103, 109, 102, 104,  98, 100, 106,  90,  97, 108, 130,
       105,  92])

In [49]:
df.Pulse.value_counts()

Pulse
100    6
103    4
102    3
98     3
110    2
117    2
109    2
104    2
92     2
106    1
90     1
97     1
108    1
130    1
105    1
Name: count, dtype: int64

In [51]:
df.rename(columns = {"Duration":"Time"})

    Time       Date  Pulse  Maxpulse  Calories
0     60 2020-12-01    110       130     409.1
1     60 2020-12-02    117       145     479.0
2     60 2020-12-03    103       135     340.0
3     45 2020-12-04    109       175     282.4
4     45 2020-12-05    117       148     406.0
5     60 2020-12-06    102       127     300.0
6     60 2020-12-07    110       136     374.0
7     45 2020-12-08    104       134     253.3
8     30 2020-12-09    109       133     195.1
9     60 2020-12-10     98       124     269.0
10    60 2020-12-11    103       147     329.3
11    60 2020-12-12    100       120     250.7
12    60 2020-12-12    100       120     250.7
13    60 2020-12-13    106       128     345.3
14    60 2020-12-14    104       132     379.3
15    60 2020-12-15     98       123     275.0
16    60 2020-12-16     98       120     215.2
17    60 2020-12-17    100       120     300.0
18    45 2020-12-18     90       112       NaN
19    60 2020-12-19    103       123     323.0
20    45 2020-12-20     97       125     243.0
21    60 2020-12-21    108       131     364.2
22    45        NaT    100       119     282.0
23    60 2020-12-23    130       101     300.0
24    45 2020-12-24    105       132     246.0
25    60 2020-12-25    102       126     334.5
26    60 2020-12-26    100       120     250.0
27    60 2020-12-27     92       118     241.0
28    60 2020-12-28    103       132       NaN
29    60 2020-12-29    100       132     280.0
30    60 2020-12-30    102       129     380.3
31    60 2020-12-31     92       115     243.0

In [52]:
df.sort_values(by = "Duration")

    Duration       Date  Pulse  Maxpulse  Calories
8         30 2020-12-09    109       133     195.1
3         45 2020-12-04    109       175     282.4
7         45 2020-12-08    104       134     253.3
4         45 2020-12-05    117       148     406.0
24        45 2020-12-24    105       132     246.0
22        45        NaT    100       119     282.0
20        45 2020-12-20     97       125     243.0
18        45 2020-12-18     90       112       NaN
6         60 2020-12-07    110       136     374.0
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
2         60 2020-12-03    103       135     340.0
1         60 2020-12-02    117       145     479.0
5         60 2020-12-06    102       127     300.0
0         60 2020-12-01    110       130     409.1
15        60 2020-12-15     98       123     275.0
14        60 2020-12-14    104       132     379.3
13        60 2020-12-13    106       128     345.3
12        60 2020-12-12    100       120     250.7
19        60 2020-12-19    103       123     323.0
17        60 2020-12-17    100       120     300.0
21        60 2020-12-21    108       131     364.2
16        60 2020-12-16     98       120     215.2
23        60 2020-12-23    130       101     300.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [55]:
df.sort_values(by = "Duration", ascending = False)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
11        60 2020-12-12    100       120     250.7
10        60 2020-12-11    103       147     329.3
9         60 2020-12-10     98       124     269.0
14        60 2020-12-14    104       132     379.3
13        60 2020-12-13    106       128     345.3
15        60 2020-12-15     98       123     275.0
12        60 2020-12-12    100       120     250.7
21        60 2020-12-21    108       131     364.2
19        60 2020-12-19    103       123     323.0
17        60 2020-12-17    100       120     300.0
16        60 2020-12-16     98       120     215.2
30        60 2020-12-30    102       129     380.3
29        60 2020-12-29    100       132     280.0
31        60 2020-12-31     92       115     243.0
28        60 2020-12-28    103       132       NaN
23        60 2020-12-23    130       101     300.0
27        60 2020-12-27     92       118     241.0
26        60 2020-12-26    100       120     250.0
25        60 2020-12-25    102       126     334.5
22        45        NaT    100       119     282.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
7         45 2020-12-08    104       134     253.3
18        45 2020-12-18     90       112       NaN
20        45 2020-12-20     97       125     243.0
24        45 2020-12-24    105       132     246.0
8         30 2020-12-09    109       133     195.1

In [56]:
df.sort_index()

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [57]:
df.groupby("Duration").Duration.count()

Duration
30     1
45     7
60    24
Name: Duration, dtype: int64

In [58]:
type(df.groupby("Duration").Duration.count())

pandas.Series

In [59]:
df.groupby(["Duration"]).Duration.agg([len])

          len
Duration
30          1
45          7
60         24

In [61]:
type(df.groupby(["Duration"]).Duration.agg([len]))

pandas.DataFrame

In [63]:
df.groupby('Duration').Pulse.min()

Duration
30    109
45     90
60     92
Name: Pulse, dtype: int64