In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [3]:
df = sns.load_dataset("tips")

In [4]:
df

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
17        16.29   3.71    Male     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
19        20.65   3.35    Male     No   Sat  Dinner     3
20        17.92   4.08    Male     No   Sat  Dinner     2
21        20.29   2.75  Female     No   Sat  Dinner     2
22        15.77   2.23  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82   3.18    Male     No   Sat  Dinner     2
25        17.81   2.34    Male     No   Sat  Dinner     4
26        13.37   2.00    Male     No   Sat  Dinner     2
27        12.69   2.00    Male     No   Sat  Dinner     2
28        21.70   4.30    Male     No   Sat  Dinner     2
29        19.65   3.00  Female     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
31        18.35   2.50    Male     No   Sat  Dinner     4
32        15.06   3.00  Female     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
34        17.78   3.27    Male     No   Sat  Dinner     2
35        24.06   3.60    Male     No   Sat  Dinner     3
36        16.31   2.00    Male     No   Sat  Dinner     3
37        16.93   3.07  Female     No   Sat  Dinner     3
38        18.69   2.31    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
40        16.04   2.24    Male     No   Sat  Dinner     3
41        17.46   2.54    Male     No   Sun  Dinner     2
42        13.94   3.06    Male     No   Sun  Dinner     2
43         9.68   1.32    Male     No   Sun  Dinner     2
44        30.40   5.60    Male     No   Sun  Dinner     4
45        18.29   3.00    Male     No   Sun  Dinner     2
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
49        18.04   3.00    Male     No   Sun  Dinner     2
50        12.54   2.50    Male     No   Sun  Dinner     2
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
53         9.94   1.56    Male     No   Sun  Dinner     2
54        25.56   4.34    Male     No   Sun  Dinner     4
55        19.49   3.51    Male     No   Sun  Dinner     2
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
58        11.24   1.76    Male    Yes   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
61        13.81   2.00    Male    Yes   Sat  Dinner     2
62        11.02   1.98    Male    Yes   Sat  Dinner     2
63        18.29   3.76    Male    Yes   Sat  Dinner     4
64        17.59   2.64    Male     No   Sat  Dinner     3
65        20.08   3.15    Male     No   Sat  Dinner     3
66        16.45   2.47  Female     No   Sat  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
68        20.23   2.01    Male     No   Sat  Dinner     2
69        15.01   2.09    Male    Yes   Sat  Dinner     2
70        12.02   1.97    Male     No   Sat  Dinner     2
71        17.07   3.00  Female     No   Sat  Dinner     3
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
74        14.73   2.20  Female     No   Sat  Dinner     2
75        10.51   1.25    Male     No   Sat  Dinner     2
76        17.92   3.08    Male    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
78        22.76   3.00    Male     No  Thur   Lunch     2
79        17.29   2.71    Male     No  Thur   Lunch     2
80        19.44   3.00    Male    Yes  Thur   Lunch     2
81        16.66   3.40    Male     No  Thur   Lunch     2
82        10.07   1.83  Female     No  Thur   Lunch     1
83        32.68   5.00    Male    Yes  Thur   Lunch     2
84        15.98   2.03    Male     No  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
86        13.03   2.00    Male     No  Thur   Lunch     2
87        18.28   4.00    Male     No  Thur   Lunch     2
88        24.71   5.85    Male     No  Thur   Lunch     2
89        21.16   3.00    Male     No  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
91        22.49   3.50    Male     No   Fri  Dinner     2
92         5.75   1.00  Female    Yes   Fri  Dinner     2
93        16.32   4.30  Female    Yes   Fri  Dinner     2
94        22.75   3.25  Female     No   Fri  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
96        27.28   4.00    Male    Yes   Fri  Dinner     2
97        12.03   1.50    Male    Yes   Fri  Dinner     2
98        21.01   3.00    Male    Yes   Fri  Dinner     2
99        12.46   1.50    Male     No   Fri  Dinner     2
100       11.35   2.50  Female    Yes   Fri  Dinner     2
101       15.38   3.00  Female    Yes   Fri  Dinner     2
102       44.30   2.50  Female    Yes   Sat  Dinner     3
103       22.42   3.48  Female    Yes   Sat  Dinner     2
104       20.92   4.08  Female     No   Sat  Dinner     2
105       15.36   1.64    Male    Yes   Sat  Dinner     2
106       20.49   4.06    Male    Yes   Sat  Dinner     2
107       25.21   4.29    Male    Yes   Sat  Dinner     2
108       18.24   3.76    Male     No   Sat  Dinner     2
109       14.31   4.00  Female    Yes   Sat  Dinner     2
110       14.00   3.00    Male     No   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
112       38.07   4.00    Male     No   Sun  Dinner     3
113       23.95   2.55    Male     No   Sun  Dinner     2
114       25.71   4.00  Female     No   Sun  Dinner     3
115       17.31   3.50  Female     No   Sun  Dinner     2
116       29.93   5.07    Male     No   Sun  Dinner     4
117       10.65   1.50  Female     No  Thur   Lunch     2
118       12.43   1.80  Female     No  Thur   Lunch     2
119       24.08   2.92  Female     No  Thur   Lunch     4
120       11.69   2.31    Male     No  Thur   Lunch     2
121       13.42   1.68  Female     No  Thur   Lunch     2
122       14.26   2.50    Male     No  Thur   Lunch     2
123       15.95   2.00    Male     No  Thur   Lunch     2
124       12.48   2.52  Female     No  Thur   Lunch     2
125       29.80   4.20  Female     No  Thur   Lunch     6
126        8.52   1.48    Male     No  Thur   Lunch     2
127       14.52   2.00  Female     No  Thur   Lunch     2
128       11.38   2.00  Female     No  Thur   Lunch     2
129       22.82   2.18    Male     No  Thur   Lunch     3
130       19.08   1.50    Male     No  Thur   Lunch     2
131       20.27   2.83  Female     No  Thur   Lunch     2
132       11.17   1.50  Female     No  Thur   Lunch     2
133       12.26   2.00  Female     No  Thur   Lunch     2
134       18.26   3.25  Female     No  Thur   Lunch     2
135        8.51   1.25  Female     No  Thur   Lunch     2
136       10.33   2.00  Female     No  Thur   Lunch     2
137       14.15   2.00  Female     No  Thur   Lunch     2
138       16.00   2.00    Male    Yes  Thur   Lunch     2
139       13.16   2.75  Female     No  Thur   Lunch     2
140       17.47   3.50  Female     No  Thur   Lunch     2
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
144       16.43   2.30  Female     No  Thur   Lunch     2
145        8.35   1.50  Female     No  Thur   Lunch     2
146       18.64   1.36  Female     No  Thur   Lunch     3
147       11.87   1.63  Female     No  Thur   Lunch     2
148        9.78   1.73    Male     No  Thur   Lunch     2
149        7.51   2.00    Male     No  Thur   Lunch     2
150       14.07   2.50    Male     No   Sun  Dinner     2
151       13.13   2.00    Male     No   Sun  Dinner     2
152       17.26   2.74    Male     No   Sun  Dinner     3
153       24.55   2.00    Male     No   Sun  Dinner     4
154       19.77   2.00    Male     No   Sun  Dinner     4
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
157       25.00   3.75  Female     No   Sun  Dinner     4
158       13.39   2.61  Female     No   Sun  Dinner     2
159       16.49   2.00    Male     No   Sun  Dinner     4
160       21.50   3.50    Male     No   Sun  Dinner     4
161       12.66   2.50    Male     No   Sun  Dinner     2
162       16.21   2.00  Female     No   Sun  Dinner     3
163       13.81   2.00    Male     No   Sun  Dinner     2
164       17.51   3.00  Female    Yes   Sun  Dinner     2
165       24.52   3.48    Male     No   Sun  Dinner     3
166       20.76   2.24    Male     No   Sun  Dinner     2
167       31.71   4.50    Male     No   Sun  Dinner     4
168       10.59   1.61  Female    Yes   Sat  Dinner     2
169       10.63   2.00  Female    Yes   Sat  Dinner     2
170       50.81  10.00    Male    Yes   Sat  Dinner     3
171       15.81   3.16    Male    Yes   Sat  Dinner     2
172        7.25   5.15    Male    Yes   Sun  Dinner     2
173       31.85   3.18    Male    Yes   Sun  Dinner     2
174       16.82   4.00    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
176       17.89   2.00    Male    Yes   Sun  Dinner     2
177       14.48   2.00    Male    Yes   Sun  Dinner     2
178        9.60   4.00  Female    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
184       40.55   3.00    Male    Yes   Sun  Dinner     2
185       20.69   5.00    Male     No   Sun  Dinner     5
186       20.90   3.50  Female    Yes   Sun  Dinner     3
187       30.46   2.00    Male    Yes   Sun  Dinner     5
188       18.15   3.50  Female    Yes   Sun  Dinner     3
189       23.10   4.00    Male    Yes   Sun  Dinner     3
190       15.69   1.50    Male    Yes   Sun  Dinner     2
191       19.81   4.19  Female    Yes  Thur   Lunch     2
192       28.44   2.56    Male    Yes  Thur   Lunch     2
193       15.48   2.02    Male    Yes  Thur   Lunch     2
194       16.58   4.00    Male    Yes  Thur   Lunch     2
195        7.56   1.44    Male     No  Thur   Lunch     2
196       10.34   2.00    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
198       13.00   2.00  Female    Yes  Thur   Lunch     2
199       13.51   2.00    Male    Yes  Thur   Lunch     2
200       18.71   4.00    Male    Yes  Thur   Lunch     3
201       12.74   2.01  Female    Yes  Thur   Lunch     2
202       13.00   2.00  Female    Yes  Thur   Lunch     2
203       16.40   2.50  Female    Yes  Thur   Lunch     2
204       20.53   4.00    Male    Yes  Thur   Lunch     4
205       16.47   3.23  Female    Yes  Thur   Lunch     3
206       26.59   3.41    Male    Yes   Sat  Dinner     3
207       38.73   3.00    Male    Yes   Sat  Dinner     4
208       24.27   2.03    Male    Yes   Sat  Dinner     2
209       12.76   2.23  Female    Yes   Sat  Dinner     2
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
213       13.27   2.50  Female    Yes   Sat  Dinner     2
214       28.17   6.50  Female    Yes   Sat  Dinner     3
215       12.90   1.10  Female    Yes   Sat  Dinner     2
216       28.15   3.00    Male    Yes   Sat  Dinner     5
217       11.59   1.50    Male    Yes   Sat  Dinner     2
218        7.74   1.44    Male    Yes   Sat  Dinner     2
219       30.14   3.09  Female    Yes   Sat  Dinner     4
220       12.16   2.20    Male    Yes   Fri   Lunch     2
221       13.42   3.48  Female    Yes   Fri   Lunch     2
222        8.58   1.92    Male    Yes   Fri   Lunch     1
223       15.98   3.00  Female     No   Fri   Lunch     3
224       13.42   1.58    Male    Yes   Fri   Lunch     2
225       16.27   2.50  Female    Yes   Fri   Lunch     2
226       10.09   2.00  Female    Yes   Fri   Lunch     2
227       20.45   3.00    Male     No   Sat  Dinner     4
228       13.28   2.72    Male     No   Sat  Dinner     2
229       22.12   2.88  Female    Yes   Sat  Dinner     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
231       15.69   3.00    Male    Yes   Sat  Dinner     3
232       11.61   3.39    Male     No   Sat  Dinner     2
233       10.77   1.47    Male     No   Sat  Dinner     2
234       15.53   3.00    Male    Yes   Sat  Dinner     2
235       10.07   1.25    Male     No   Sat  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3
240       27.18   2.00  Female    Yes   Sat  Dinner     2
241       22.67   2.00    Male    Yes   Sat  Dinner     2
242       17.82   1.75    Male     No   Sat  Dinner     2
243       18.78   3.00  Female     No  Thur  Dinner     2

In [5]:
df.info

<bound method DataFrame.info of      total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
17        16.29   3.71    Male     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
19        20.65   3.35    Male     No   Sat  Dinner     3
20        17.92   4.08    Male     No   Sat  Dinner     2
21        20.29   2.75  Female     No   Sat  Dinner     2
22        15.77   2.23  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82   3.18    Male     No   Sat  Dinner     2
25        17.81   2.34    Male     No   Sat  Dinner     4
26        13.37   2.00    Male     No   Sat  Dinner     2
27        12.69   2.00    Male     No   Sat  Dinner     2
28        21.70   4.30    Male     No   Sat  Dinner     2
29        19.65   3.00  Female     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
31        18.35   2.50    Male     No   Sat  Dinner     4
32        15.06   3.00  Female     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
34        17.78   3.27    Male     No   Sat  Dinner     2
35        24.06   3.60    Male     No   Sat  Dinner     3
36        16.31   2.00    Male     No   Sat  Dinner     3
37        16.93   3.07  Female     No   Sat  Dinner     3
38        18.69   2.31    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
40        16.04   2.24    Male     No   Sat  Dinner     3
41        17.46   2.54    Male     No   Sun  Dinner     2
42        13.94   3.06    Male     No   Sun  Dinner     2
43         9.68   1.32    Male     No   Sun  Dinner     2
44        30.40   5.60    Male     No   Sun  Dinner     4
45        18.29   3.00    Male     No   Sun  Dinner     2
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
49        18.04   3.00    Male     No   Sun  Dinner     2
50        12.54   2.50    Male     No   Sun  Dinner     2
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
53         9.94   1.56    Male     No   Sun  Dinner     2
54        25.56   4.34    Male     No   Sun  Dinner     4
55        19.49   3.51    Male     No   Sun  Dinner     2
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
58        11.24   1.76    Male    Yes   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
61        13.81   2.00    Male    Yes   Sat  Dinner     2
62        11.02   1.98    Male    Yes   Sat  Dinner     2
63        18.29   3.76    Male    Yes   Sat  Dinner     4
64        17.59   2.64    Male     No   Sat  Dinner     3
65        20.08   3.15    Male     No   Sat  Dinner     3
66        16.45   2.47  Female     No   Sat  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
68        20.23   2.01    Male     No   Sat  Dinner     2
69        15.01   2.09    Male    Yes   Sat  Dinner     2
70        12.02   1.97    Male     No   Sat  Dinner     2
71        17.07   3.00  Female     No   Sat  Dinner     3
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
74        14.73   2.20  Female     No   Sat  Dinner     2
75        10.51   1.25    Male     No   Sat  Dinner     2
76        17.92   3.08    Male    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
78        22.76   3.00    Male     No  Thur   Lunch     2
79        17.29   2.71    Male     No  Thur   Lunch     2
80        19.44   3.00    Male    Yes  Thur   Lunch     2
81        16.66   3.40    Male     No  Thur   Lunch     2
82        10.07   1.83  Female     No  Thur   Lunch     1
83        32.68   5.00    Male    Yes  Thur   Lunch     2
84        15.98   2.03    Male     No  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
86        13.03   2.00    Male     No  Thur   Lunch     2
87        18.28   4.00    Male     No  Thur   Lunch     2
88        24.71   5.85    Male     No  Thur   Lunch     2
89        21.16   3.00    Male     No  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
91        22.49   3.50    Male     No   Fri  Dinner     2
92         5.75   1.00  Female    Yes   Fri  Dinner     2
93        16.32   4.30  Female    Yes   Fri  Dinner     2
94        22.75   3.25  Female     No   Fri  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
96        27.28   4.00    Male    Yes   Fri  Dinner     2
97        12.03   1.50    Male    Yes   Fri  Dinner     2
98        21.01   3.00    Male    Yes   Fri  Dinner     2
99        12.46   1.50    Male     No   Fri  Dinner     2
100       11.35   2.50  Female    Yes   Fri  Dinner     2
101       15.38   3.00  Female    Yes   Fri  Dinner     2
102       44.30   2.50  Female    Yes   Sat  Dinner     3
103       22.42   3.48  Female    Yes   Sat  Dinner     2
104       20.92   4.08  Female     No   Sat  Dinner     2
105       15.36   1.64    Male    Yes   Sat  Dinner     2
106       20.49   4.06    Male    Yes   Sat  Dinner     2
107       25.21   4.29    Male    Yes   Sat  Dinner     2
108       18.24   3.76    Male     No   Sat  Dinner     2
109       14.31   4.00  Female    Yes   Sat  Dinner     2
110       14.00   3.00    Male     No   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
112       38.07   4.00    Male     No   Sun  Dinner     3
113       23.95   2.55    Male     No   Sun  Dinner     2
114       25.71   4.00  Female     No   Sun  Dinner     3
115       17.31   3.50  Female     No   Sun  Dinner     2
116       29.93   5.07    Male     No   Sun  Dinner     4
117       10.65   1.50  Female     No  Thur   Lunch     2
118       12.43   1.80  Female     No  Thur   Lunch     2
119       24.08   2.92  Female     No  Thur   Lunch     4
120       11.69   2.31    Male     No  Thur   Lunch     2
121       13.42   1.68  Female     No  Thur   Lunch     2
122       14.26   2.50    Male     No  Thur   Lunch     2
123       15.95   2.00    Male     No  Thur   Lunch     2
124       12.48   2.52  Female     No  Thur   Lunch     2
125       29.80   4.20  Female     No  Thur   Lunch     6
126        8.52   1.48    Male     No  Thur   Lunch     2
127       14.52   2.00  Female     No  Thur   Lunch     2
128       11.38   2.00  Female     No  Thur   Lunch     2
129       22.82   2.18    Male     No  Thur   Lunch     3
130       19.08   1.50    Male     No  Thur   Lunch     2
131       20.27   2.83  Female     No  Thur   Lunch     2
132       11.17   1.50  Female     No  Thur   Lunch     2
133       12.26   2.00  Female     No  Thur   Lunch     2
134       18.26   3.25  Female     No  Thur   Lunch     2
135        8.51   1.25  Female     No  Thur   Lunch     2
136       10.33   2.00  Female     No  Thur   Lunch     2
137       14.15   2.00  Female     No  Thur   Lunch     2
138       16.00   2.00    Male    Yes  Thur   Lunch     2
139       13.16   2.75  Female     No  Thur   Lunch     2
140       17.47   3.50  Female     No  Thur   Lunch     2
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
144       16.43   2.30  Female     No  Thur   Lunch     2
145        8.35   1.50  Female     No  Thur   Lunch     2
146       18.64   1.36  Female     No  Thur   Lunch     3
147       11.87   1.63  Female     No  Thur   Lunch     2
148        9.78   1.73    Male     No  Thur   Lunch     2
149        7.51   2.00    Male     No  Thur   Lunch     2
150       14.07   2.50    Male     No   Sun  Dinner     2
151       13.13   2.00    Male     No   Sun  Dinner     2
152       17.26   2.74    Male     No   Sun  Dinner     3
153       24.55   2.00    Male     No   Sun  Dinner     4
154       19.77   2.00    Male     No   Sun  Dinner     4
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
157       25.00   3.75  Female     No   Sun  Dinner     4
158       13.39   2.61  Female     No   Sun  Dinner     2
159       16.49   2.00    Male     No   Sun  Dinner     4
160       21.50   3.50    Male     No   Sun  Dinner     4
161       12.66   2.50    Male     No   Sun  Dinner     2
162       16.21   2.00  Female     No   Sun  Dinner     3
163       13.81   2.00    Male     No   Sun  Dinner     2
164       17.51   3.00  Female    Yes   Sun  Dinner     2
165       24.52   3.48    Male     No   Sun  Dinner     3
166       20.76   2.24    Male     No   Sun  Dinner     2
167       31.71   4.50    Male     No   Sun  Dinner     4
168       10.59   1.61  Female    Yes   Sat  Dinner     2
169       10.63   2.00  Female    Yes   Sat  Dinner     2
170       50.81  10.00    Male    Yes   Sat  Dinner     3
171       15.81   3.16    Male    Yes   Sat  Dinner     2
172        7.25   5.15    Male    Yes   Sun  Dinner     2
173       31.85   3.18    Male    Yes   Sun  Dinner     2
174       16.82   4.00    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
176       17.89   2.00    Male    Yes   Sun  Dinner     2
177       14.48   2.00    Male    Yes   Sun  Dinner     2
178        9.60   4.00  Female    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
184       40.55   3.00    Male    Yes   Sun  Dinner     2
185       20.69   5.00    Male     No   Sun  Dinner     5
186       20.90   3.50  Female    Yes   Sun  Dinner     3
187       30.46   2.00    Male    Yes   Sun  Dinner     5
188       18.15   3.50  Female    Yes   Sun  Dinner     3
189       23.10   4.00    Male    Yes   Sun  Dinner     3
190       15.69   1.50    Male    Yes   Sun  Dinner     2
191       19.81   4.19  Female    Yes  Thur   Lunch     2
192       28.44   2.56    Male    Yes  Thur   Lunch     2
193       15.48   2.02    Male    Yes  Thur   Lunch     2
194       16.58   4.00    Male    Yes  Thur   Lunch     2
195        7.56   1.44    Male     No  Thur   Lunch     2
196       10.34   2.00    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
198       13.00   2.00  Female    Yes  Thur   Lunch     2
199       13.51   2.00    Male    Yes  Thur   Lunch     2
200       18.71   4.00    Male    Yes  Thur   Lunch     3
201       12.74   2.01  Female    Yes  Thur   Lunch     2
202       13.00   2.00  Female    Yes  Thur   Lunch     2
203       16.40   2.50  Female    Yes  Thur   Lunch     2
204       20.53   4.00    Male    Yes  Thur   Lunch     4
205       16.47   3.23  Female    Yes  Thur   Lunch     3
206       26.59   3.41    Male    Yes   Sat  Dinner     3
207       38.73   3.00    Male    Yes   Sat  Dinner     4
208       24.27   2.03    Male    Yes   Sat  Dinner     2
209       12.76   2.23  Female    Yes   Sat  Dinner     2
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
213       13.27   2.50  Female    Yes   Sat  Dinner     2
214       28.17   6.50  Female    Yes   Sat  Dinner     3
215       12.90   1.10  Female    Yes   Sat  Dinner     2
216       28.15   3.00    Male    Yes   Sat  Dinner     5
217       11.59   1.50    Male    Yes   Sat  Dinner     2
218        7.74   1.44    Male    Yes   Sat  Dinner     2
219       30.14   3.09  Female    Yes   Sat  Dinner     4
220       12.16   2.20    Male    Yes   Fri   Lunch     2
221       13.42   3.48  Female    Yes   Fri   Lunch     2
222        8.58   1.92    Male    Yes   Fri   Lunch     1
223       15.98   3.00  Female     No   Fri   Lunch     3
224       13.42   1.58    Male    Yes   Fri   Lunch     2
225       16.27   2.50  Female    Yes   Fri   Lunch     2
226       10.09   2.00  Female    Yes   Fri   Lunch     2
227       20.45   3.00    Male     No   Sat  Dinner     4
228       13.28   2.72    Male     No   Sat  Dinner     2
229       22.12   2.88  Female    Yes   Sat  Dinner     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
231       15.69   3.00    Male    Yes   Sat  Dinner     3
232       11.61   3.39    Male     No   Sat  Dinner     2
233       10.77   1.47    Male     No   Sat  Dinner     2
234       15.53   3.00    Male    Yes   Sat  Dinner     2
235       10.07   1.25    Male     No   Sat  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3
240       27.18   2.00  Female    Yes   Sat  Dinner     2
241       22.67   2.00    Male    Yes   Sat  Dinner     2
242       17.82   1.75    Male     No   Sat  Dinner     2
243       18.78   3.00  Female     No  Thur  Dinner     2>

In [6]:
df.shape

(244, 7)

In [7]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [9]:
dummydata = pd.get_dummies(df)

In [10]:
dummydata.head()

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,False,True,False,True,False,False,False,True,False,True
1,10.34,1.66,3,True,False,False,True,False,False,False,True,False,True
2,21.01,3.50,3,True,False,False,True,False,False,False,True,False,True
3,23.68,3.31,2,True,False,False,True,False,False,False,True,False,True
4,24.59,3.61,4,False,True,False,True,False,False,False,True,False,True

In [11]:
onh = OneHotEncoder(sparse_output=False)

In [12]:
onh

OneHotEncoder(sparse_output=False)

In [13]:
oh_enco_arr = onh.fit_transform(df[['sex', 'smoker', 'day', 'time']])

In [14]:
oh_enco_arr

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [15]:
dummydata.keys()

Index(['total_bill', 'tip', 'size', 'sex_Male', 'sex_Female', 'smoker_Yes',
       'smoker_No', 'day_Thur', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Lunch',
       'time_Dinner'],
      dtype='str')

In [16]:
oh_enco_arr = pd.DataFrame(oh_enco_arr, columns=['sex_Female', 'sex_Male', 'smoker_No', 'smoker_Yes', 'day_Fri', 'day_Sat', 'day_Sun', 'day_Thur', 'time_Dinner', 'timer_Lunch'])

In [17]:
oh_enco_arr

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,timer_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
5,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
6,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
7,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
8,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
9,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
11,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
12,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
13,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
14,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
15,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
16,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
17,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
18,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
20,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
21,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
22,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
23,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
24,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
25,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
26,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
27,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
28,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
30,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
31,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
32,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
33,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
34,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
35,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
36,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
37,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
38,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
39,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
40,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
41,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
42,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
43,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
44,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
45,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
46,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
47,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
48,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
49,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
50,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
51,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
52,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
53,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
54,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
55,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
56,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
57,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
58,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
59,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
60,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
61,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
62,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
63,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
64,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
65,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
66,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
67,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
68,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
69,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
70,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
71,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
72,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
73,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
74,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
75,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
76,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
77,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
78,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
79,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
81,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
82,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
83,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
84,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
86,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
87,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
88,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
89,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
90,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
91,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
92,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
93,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
94,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
95,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
96,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
97,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
98,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
99,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
100,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
101,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
102,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
103,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
104,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
105,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
106,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
107,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
108,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
109,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
110,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
111,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
112,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
113,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
114,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
115,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
116,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
117,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
118,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
119,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
120,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
121,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
122,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
123,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
124,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
125,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
126,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
127,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
128,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
129,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
130,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
131,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
132,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
133,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
134,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
135,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
136,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
137,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
138,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
139,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
140,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
141,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
142,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
143,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
144,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
145,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
146,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
147,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
148,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
149,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
150,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
151,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
152,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
153,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
154,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
155,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
156,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
157,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
158,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
159,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
160,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
161,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
162,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
163,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
164,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
165,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
166,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
167,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
168,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
169,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
170,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
171,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
172,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
173,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
174,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
175,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
176,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
177,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
178,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
179,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
180,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
181,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
182,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
183,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
184,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
185,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
186,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
187,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
188,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
189,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
190,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
191,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
192,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
193,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
194,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
195,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
196,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
197,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
198,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
199,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
200,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
201,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
202,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
203,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
204,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
205,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
206,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
207,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
208,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
209,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
210,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
211,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
212,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
213,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
214,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
215,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
216,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
217,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
218,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
219,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
220,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
221,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
222,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
223,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
224,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
225,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
226,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
227,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
228,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
229,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
230,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
231,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
232,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
233,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
234,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
235,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
236,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
237,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
238,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
243,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [18]:
df = sns.load_dataset('tips')

In [19]:
df

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
17        16.29   3.71    Male     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
19        20.65   3.35    Male     No   Sat  Dinner     3
20        17.92   4.08    Male     No   Sat  Dinner     2
21        20.29   2.75  Female     No   Sat  Dinner     2
22        15.77   2.23  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82   3.18    Male     No   Sat  Dinner     2
25        17.81   2.34    Male     No   Sat  Dinner     4
26        13.37   2.00    Male     No   Sat  Dinner     2
27        12.69   2.00    Male     No   Sat  Dinner     2
28        21.70   4.30    Male     No   Sat  Dinner     2
29        19.65   3.00  Female     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
31        18.35   2.50    Male     No   Sat  Dinner     4
32        15.06   3.00  Female     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
34        17.78   3.27    Male     No   Sat  Dinner     2
35        24.06   3.60    Male     No   Sat  Dinner     3
36        16.31   2.00    Male     No   Sat  Dinner     3
37        16.93   3.07  Female     No   Sat  Dinner     3
38        18.69   2.31    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
40        16.04   2.24    Male     No   Sat  Dinner     3
41        17.46   2.54    Male     No   Sun  Dinner     2
42        13.94   3.06    Male     No   Sun  Dinner     2
43         9.68   1.32    Male     No   Sun  Dinner     2
44        30.40   5.60    Male     No   Sun  Dinner     4
45        18.29   3.00    Male     No   Sun  Dinner     2
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
49        18.04   3.00    Male     No   Sun  Dinner     2
50        12.54   2.50    Male     No   Sun  Dinner     2
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
53         9.94   1.56    Male     No   Sun  Dinner     2
54        25.56   4.34    Male     No   Sun  Dinner     4
55        19.49   3.51    Male     No   Sun  Dinner     2
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
58        11.24   1.76    Male    Yes   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
61        13.81   2.00    Male    Yes   Sat  Dinner     2
62        11.02   1.98    Male    Yes   Sat  Dinner     2
63        18.29   3.76    Male    Yes   Sat  Dinner     4
64        17.59   2.64    Male     No   Sat  Dinner     3
65        20.08   3.15    Male     No   Sat  Dinner     3
66        16.45   2.47  Female     No   Sat  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
68        20.23   2.01    Male     No   Sat  Dinner     2
69        15.01   2.09    Male    Yes   Sat  Dinner     2
70        12.02   1.97    Male     No   Sat  Dinner     2
71        17.07   3.00  Female     No   Sat  Dinner     3
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
74        14.73   2.20  Female     No   Sat  Dinner     2
75        10.51   1.25    Male     No   Sat  Dinner     2
76        17.92   3.08    Male    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
78        22.76   3.00    Male     No  Thur   Lunch     2
79        17.29   2.71    Male     No  Thur   Lunch     2
80        19.44   3.00    Male    Yes  Thur   Lunch     2
81        16.66   3.40    Male     No  Thur   Lunch     2
82        10.07   1.83  Female     No  Thur   Lunch     1
83        32.68   5.00    Male    Yes  Thur   Lunch     2
84        15.98   2.03    Male     No  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
86        13.03   2.00    Male     No  Thur   Lunch     2
87        18.28   4.00    Male     No  Thur   Lunch     2
88        24.71   5.85    Male     No  Thur   Lunch     2
89        21.16   3.00    Male     No  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
91        22.49   3.50    Male     No   Fri  Dinner     2
92         5.75   1.00  Female    Yes   Fri  Dinner     2
93        16.32   4.30  Female    Yes   Fri  Dinner     2
94        22.75   3.25  Female     No   Fri  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
96        27.28   4.00    Male    Yes   Fri  Dinner     2
97        12.03   1.50    Male    Yes   Fri  Dinner     2
98        21.01   3.00    Male    Yes   Fri  Dinner     2
99        12.46   1.50    Male     No   Fri  Dinner     2
100       11.35   2.50  Female    Yes   Fri  Dinner     2
101       15.38   3.00  Female    Yes   Fri  Dinner     2
102       44.30   2.50  Female    Yes   Sat  Dinner     3
103       22.42   3.48  Female    Yes   Sat  Dinner     2
104       20.92   4.08  Female     No   Sat  Dinner     2
105       15.36   1.64    Male    Yes   Sat  Dinner     2
106       20.49   4.06    Male    Yes   Sat  Dinner     2
107       25.21   4.29    Male    Yes   Sat  Dinner     2
108       18.24   3.76    Male     No   Sat  Dinner     2
109       14.31   4.00  Female    Yes   Sat  Dinner     2
110       14.00   3.00    Male     No   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
112       38.07   4.00    Male     No   Sun  Dinner     3
113       23.95   2.55    Male     No   Sun  Dinner     2
114       25.71   4.00  Female     No   Sun  Dinner     3
115       17.31   3.50  Female     No   Sun  Dinner     2
116       29.93   5.07    Male     No   Sun  Dinner     4
117       10.65   1.50  Female     No  Thur   Lunch     2
118       12.43   1.80  Female     No  Thur   Lunch     2
119       24.08   2.92  Female     No  Thur   Lunch     4
120       11.69   2.31    Male     No  Thur   Lunch     2
121       13.42   1.68  Female     No  Thur   Lunch     2
122       14.26   2.50    Male     No  Thur   Lunch     2
123       15.95   2.00    Male     No  Thur   Lunch     2
124       12.48   2.52  Female     No  Thur   Lunch     2
125       29.80   4.20  Female     No  Thur   Lunch     6
126        8.52   1.48    Male     No  Thur   Lunch     2
127       14.52   2.00  Female     No  Thur   Lunch     2
128       11.38   2.00  Female     No  Thur   Lunch     2
129       22.82   2.18    Male     No  Thur   Lunch     3
130       19.08   1.50    Male     No  Thur   Lunch     2
131       20.27   2.83  Female     No  Thur   Lunch     2
132       11.17   1.50  Female     No  Thur   Lunch     2
133       12.26   2.00  Female     No  Thur   Lunch     2
134       18.26   3.25  Female     No  Thur   Lunch     2
135        8.51   1.25  Female     No  Thur   Lunch     2
136       10.33   2.00  Female     No  Thur   Lunch     2
137       14.15   2.00  Female     No  Thur   Lunch     2
138       16.00   2.00    Male    Yes  Thur   Lunch     2
139       13.16   2.75  Female     No  Thur   Lunch     2
140       17.47   3.50  Female     No  Thur   Lunch     2
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
144       16.43   2.30  Female     No  Thur   Lunch     2
145        8.35   1.50  Female     No  Thur   Lunch     2
146       18.64   1.36  Female     No  Thur   Lunch     3
147       11.87   1.63  Female     No  Thur   Lunch     2
148        9.78   1.73    Male     No  Thur   Lunch     2
149        7.51   2.00    Male     No  Thur   Lunch     2
150       14.07   2.50    Male     No   Sun  Dinner     2
151       13.13   2.00    Male     No   Sun  Dinner     2
152       17.26   2.74    Male     No   Sun  Dinner     3
153       24.55   2.00    Male     No   Sun  Dinner     4
154       19.77   2.00    Male     No   Sun  Dinner     4
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
157       25.00   3.75  Female     No   Sun  Dinner     4
158       13.39   2.61  Female     No   Sun  Dinner     2
159       16.49   2.00    Male     No   Sun  Dinner     4
160       21.50   3.50    Male     No   Sun  Dinner     4
161       12.66   2.50    Male     No   Sun  Dinner     2
162       16.21   2.00  Female     No   Sun  Dinner     3
163       13.81   2.00    Male     No   Sun  Dinner     2
164       17.51   3.00  Female    Yes   Sun  Dinner     2
165       24.52   3.48    Male     No   Sun  Dinner     3
166       20.76   2.24    Male     No   Sun  Dinner     2
167       31.71   4.50    Male     No   Sun  Dinner     4
168       10.59   1.61  Female    Yes   Sat  Dinner     2
169       10.63   2.00  Female    Yes   Sat  Dinner     2
170       50.81  10.00    Male    Yes   Sat  Dinner     3
171       15.81   3.16    Male    Yes   Sat  Dinner     2
172        7.25   5.15    Male    Yes   Sun  Dinner     2
173       31.85   3.18    Male    Yes   Sun  Dinner     2
174       16.82   4.00    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
176       17.89   2.00    Male    Yes   Sun  Dinner     2
177       14.48   2.00    Male    Yes   Sun  Dinner     2
178        9.60   4.00  Female    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
184       40.55   3.00    Male    Yes   Sun  Dinner     2
185       20.69   5.00    Male     No   Sun  Dinner     5
186       20.90   3.50  Female    Yes   Sun  Dinner     3
187       30.46   2.00    Male    Yes   Sun  Dinner     5
188       18.15   3.50  Female    Yes   Sun  Dinner     3
189       23.10   4.00    Male    Yes   Sun  Dinner     3
190       15.69   1.50    Male    Yes   Sun  Dinner     2
191       19.81   4.19  Female    Yes  Thur   Lunch     2
192       28.44   2.56    Male    Yes  Thur   Lunch     2
193       15.48   2.02    Male    Yes  Thur   Lunch     2
194       16.58   4.00    Male    Yes  Thur   Lunch     2
195        7.56   1.44    Male     No  Thur   Lunch     2
196       10.34   2.00    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
198       13.00   2.00  Female    Yes  Thur   Lunch     2
199       13.51   2.00    Male    Yes  Thur   Lunch     2
200       18.71   4.00    Male    Yes  Thur   Lunch     3
201       12.74   2.01  Female    Yes  Thur   Lunch     2
202       13.00   2.00  Female    Yes  Thur   Lunch     2
203       16.40   2.50  Female    Yes  Thur   Lunch     2
204       20.53   4.00    Male    Yes  Thur   Lunch     4
205       16.47   3.23  Female    Yes  Thur   Lunch     3
206       26.59   3.41    Male    Yes   Sat  Dinner     3
207       38.73   3.00    Male    Yes   Sat  Dinner     4
208       24.27   2.03    Male    Yes   Sat  Dinner     2
209       12.76   2.23  Female    Yes   Sat  Dinner     2
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
213       13.27   2.50  Female    Yes   Sat  Dinner     2
214       28.17   6.50  Female    Yes   Sat  Dinner     3
215       12.90   1.10  Female    Yes   Sat  Dinner     2
216       28.15   3.00    Male    Yes   Sat  Dinner     5
217       11.59   1.50    Male    Yes   Sat  Dinner     2
218        7.74   1.44    Male    Yes   Sat  Dinner     2
219       30.14   3.09  Female    Yes   Sat  Dinner     4
220       12.16   2.20    Male    Yes   Fri   Lunch     2
221       13.42   3.48  Female    Yes   Fri   Lunch     2
222        8.58   1.92    Male    Yes   Fri   Lunch     1
223       15.98   3.00  Female     No   Fri   Lunch     3
224       13.42   1.58    Male    Yes   Fri   Lunch     2
225       16.27   2.50  Female    Yes   Fri   Lunch     2
226       10.09   2.00  Female    Yes   Fri   Lunch     2
227       20.45   3.00    Male     No   Sat  Dinner     4
228       13.28   2.72    Male     No   Sat  Dinner     2
229       22.12   2.88  Female    Yes   Sat  Dinner     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
231       15.69   3.00    Male    Yes   Sat  Dinner     3
232       11.61   3.39    Male     No   Sat  Dinner     2
233       10.77   1.47    Male     No   Sat  Dinner     2
234       15.53   3.00    Male    Yes   Sat  Dinner     2
235       10.07   1.25    Male     No   Sat  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3
240       27.18   2.00  Female    Yes   Sat  Dinner     2
241       22.67   2.00    Male    Yes   Sat  Dinner     2
242       17.82   1.75    Male     No   Sat  Dinner     2
243       18.78   3.00  Female     No  Thur  Dinner     2

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le = LabelEncoder()

In [24]:
df2 = df[['sex', 'smoker', 'day', 'time']]

In [25]:
le.fit_transform(df2['sex'])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [26]:
le.fit_transform(df2['smoker'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0])

In [27]:
le.fit_transform(df2['day'])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [28]:
le.fit_transform(df2['time'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [29]:
df2['day'] = le.fit_transform(df2['day'])

In [30]:
df2['day']

0      2
1      2
2      2
3      2
4      2
5      2
6      2
7      2
8      2
9      2
10     2
11     2
12     2
13     2
14     2
15     2
16     2
17     2
18     2
19     1
20     1
21     1
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
30     1
31     1
32     1
33     1
34     1
35     1
36     1
37     1
38     1
39     1
40     1
41     2
42     2
43     2
44     2
45     2
46     2
47     2
48     2
49     2
50     2
51     2
52     2
53     2
54     2
55     2
56     1
57     1
58     1
59     1
60     1
61     1
62     1
63     1
64     1
65     1
66     1
67     1
68     1
69     1
70     1
71     1
72     1
73     1
74     1
75     1
76     1
77     3
78     3
79     3
80     3
81     3
82     3
83     3
84     3
85     3
86     3
87     3
88     3
89     3
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    1
103    1
104    1
105    1
106    1
107    1
108    1
109    1
110    1
111    1
112    2
113    2
114    2
115    2
116    2
117    3
118    3
119    3
120    3
121    3
122    3
123    3
124    3
125    3
126    3
127    3
128    3
129    3
130    3
131    3
132    3
133    3
134    3
135    3
136    3
137    3
138    3
139    3
140    3
141    3
142    3
143    3
144    3
145    3
146    3
147    3
148    3
149    3
150    2
151    2
152    2
153    2
154    2
155    2
156    2
157    2
158    2
159    2
160    2
161    2
162    2
163    2
164    2
165    2
166    2
167    2
168    1
169    1
170    1
171    1
172    2
173    2
174    2
175    2
176    2
177    2
178    2
179    2
180    2
181    2
182    2
183    2
184    2
185    2
186    2
187    2
188    2
189    2
190    2
191    3
192    3
193    3
194    3
195    3
196    3
197    3
198    3
199    3
200    3
201    3
202    3
203    3
204    3
205    3
206    1
207    1
208    1
209    1
210    1
211    1
212    1
213    1
214    1
215    1
216    1
217    1
218    1
219    1
220    0
221    0
222    0
223    0
224    0
225    0
226    0
227    1
228    1
229    1
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    1
239    1
240    1
241    1
242    1
243    3
Name: day, dtype: int64

In [31]:
df2['sex'] = le.fit_transform(df2['sex'])

In [32]:
df2['sex']

0      0
1      1
2      1
3      1
4      0
5      1
6      1
7      1
8      1
9      1
10     1
11     0
12     1
13     1
14     0
15     1
16     0
17     1
18     0
19     1
20     1
21     0
22     0
23     1
24     1
25     1
26     1
27     1
28     1
29     0
30     1
31     1
32     0
33     0
34     1
35     1
36     1
37     0
38     1
39     1
40     1
41     1
42     1
43     1
44     1
45     1
46     1
47     1
48     1
49     1
50     1
51     0
52     0
53     1
54     1
55     1
56     1
57     0
58     1
59     1
60     1
61     1
62     1
63     1
64     1
65     1
66     0
67     0
68     1
69     1
70     1
71     0
72     0
73     0
74     0
75     1
76     1
77     1
78     1
79     1
80     1
81     1
82     0
83     1
84     1
85     0
86     1
87     1
88     1
89     1
90     1
91     1
92     0
93     0
94     0
95     1
96     1
97     1
98     1
99     1
100    0
101    0
102    0
103    0
104    0
105    1
106    1
107    1
108    1
109    0
110    1
111    0
112    1
113    1
114    0
115    0
116    1
117    0
118    0
119    0
120    1
121    0
122    1
123    1
124    0
125    0
126    1
127    0
128    0
129    1
130    1
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    0
140    0
141    1
142    1
143    0
144    0
145    0
146    0
147    0
148    1
149    1
150    1
151    1
152    1
153    1
154    1
155    0
156    1
157    0
158    0
159    1
160    1
161    1
162    0
163    1
164    0
165    1
166    1
167    1
168    0
169    0
170    1
171    1
172    1
173    1
174    1
175    1
176    1
177    1
178    0
179    1
180    1
181    1
182    1
183    1
184    1
185    1
186    0
187    1
188    0
189    1
190    1
191    0
192    1
193    1
194    1
195    1
196    1
197    0
198    0
199    1
200    1
201    0
202    0
203    0
204    1
205    0
206    1
207    1
208    1
209    0
210    1
211    1
212    1
213    0
214    0
215    0
216    1
217    1
218    1
219    0
220    1
221    0
222    1
223    0
224    1
225    0
226    0
227    1
228    1
229    0
230    1
231    1
232    1
233    1
234    1
235    1
236    1
237    1
238    0
239    1
240    0
241    1
242    1
243    0
Name: sex, dtype: int64

In [34]:
df2['smoker'] = le.fit_transform(df2['smoker'])

In [35]:
df2['smoker']

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     1
57     0
58     1
59     0
60     1
61     1
62     1
63     1
64     0
65     0
66     0
67     1
68     0
69     1
70     0
71     0
72     1
73     1
74     0
75     0
76     1
77     0
78     0
79     0
80     1
81     0
82     0
83     1
84     0
85     0
86     0
87     0
88     0
89     0
90     1
91     0
92     1
93     1
94     0
95     1
96     1
97     1
98     1
99     0
100    1
101    1
102    1
103    1
104    0
105    1
106    1
107    1
108    0
109    1
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    0
118    0
119    0
120    0
121    0
122    0
123    0
124    0
125    0
126    0
127    0
128    0
129    0
130    0
131    0
132    0
133    0
134    0
135    0
136    0
137    0
138    1
139    0
140    0
141    0
142    0
143    0
144    0
145    0
146    0
147    0
148    0
149    0
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    0
161    0
162    0
163    0
164    1
165    0
166    0
167    0
168    1
169    1
170    1
171    1
172    1
173    1
174    1
175    1
176    1
177    1
178    1
179    1
180    1
181    1
182    1
183    1
184    1
185    0
186    1
187    1
188    1
189    1
190    1
191    1
192    1
193    1
194    1
195    0
196    1
197    1
198    1
199    1
200    1
201    1
202    1
203    1
204    1
205    1
206    1
207    1
208    1
209    1
210    1
211    1
212    0
213    1
214    1
215    1
216    1
217    1
218    1
219    1
220    1
221    1
222    1
223    0
224    1
225    1
226    1
227    0
228    0
229    1
230    1
231    1
232    0
233    0
234    1
235    0
236    1
237    1
238    0
239    0
240    1
241    1
242    0
243    0
Name: smoker, dtype: int64

In [36]:
df2['time'] = le.fit_transform(df2['time'])
df2['time']

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
30     0
31     0
32     0
33     0
34     0
35     0
36     0
37     0
38     0
39     0
40     0
41     0
42     0
43     0
44     0
45     0
46     0
47     0
48     0
49     0
50     0
51     0
52     0
53     0
54     0
55     0
56     0
57     0
58     0
59     0
60     0
61     0
62     0
63     0
64     0
65     0
66     0
67     0
68     0
69     0
70     0
71     0
72     0
73     0
74     0
75     0
76     0
77     1
78     1
79     1
80     1
81     1
82     1
83     1
84     1
85     1
86     1
87     1
88     1
89     1
90     0
91     0
92     0
93     0
94     0
95     0
96     0
97     0
98     0
99     0
100    0
101    0
102    0
103    0
104    0
105    0
106    0
107    0
108    0
109    0
110    0
111    0
112    0
113    0
114    0
115    0
116    0
117    1
118    1
119    1
120    1
121    1
122    1
123    1
124    1
125    1
126    1
127    1
128    1
129    1
130    1
131    1
132    1
133    1
134    1
135    1
136    1
137    1
138    1
139    1
140    1
141    1
142    1
143    1
144    1
145    1
146    1
147    1
148    1
149    1
150    0
151    0
152    0
153    0
154    0
155    0
156    0
157    0
158    0
159    0
160    0
161    0
162    0
163    0
164    0
165    0
166    0
167    0
168    0
169    0
170    0
171    0
172    0
173    0
174    0
175    0
176    0
177    0
178    0
179    0
180    0
181    0
182    0
183    0
184    0
185    0
186    0
187    0
188    0
189    0
190    0
191    1
192    1
193    1
194    1
195    1
196    1
197    1
198    1
199    1
200    1
201    1
202    1
203    1
204    1
205    1
206    0
207    0
208    0
209    0
210    0
211    0
212    0
213    0
214    0
215    0
216    0
217    0
218    0
219    0
220    1
221    1
222    1
223    1
224    1
225    1
226    1
227    0
228    0
229    0
230    0
231    0
232    0
233    0
234    0
235    0
236    0
237    0
238    0
239    0
240    0
241    0
242    0
243    0
Name: time, dtype: int64

In [39]:
df2 = df[['sex', 'smoker', 'day', 'time']].copy()
for col in df2.columns:
    df2[col] = le.fit_transform(df2[col])
df2.head()

   sex  smoker  day  time
0    0       0    2     0
1    1       0    2     0
2    1       0    2     0
3    1       0    2     0
4    0       0    2     0

In [41]:
for col in ["sex","smoker","day","time"]:
    df[col] = le.fit_transform(df[col])

df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4