In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
le=LabelEncoder()

In [4]:
df=sns.load_dataset("tips")

In [5]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
df.keys()

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [10]:
df2=df[["sex","smoker","day","time"]].copy()

In [11]:
df2

        sex smoker   day    time
0    Female     No   Sun  Dinner
1      Male     No   Sun  Dinner
2      Male     No   Sun  Dinner
3      Male     No   Sun  Dinner
4    Female     No   Sun  Dinner
..      ...    ...   ...     ...
239    Male     No   Sat  Dinner
240  Female    Yes   Sat  Dinner
241    Male    Yes   Sat  Dinner
242    Male     No   Sat  Dinner
243  Female     No  Thur  Dinner

[244 rows x 4 columns]

In [14]:
for col in df2.columns:
    df2[col] = le.fit_transform(df2[col])
df2

     sex  smoker  day  time
0      0       0    2     0
1      1       0    2     0
2      1       0    2     0
3      1       0    2     0
4      0       0    2     0
..   ...     ...  ...   ...
239    1       0    1     0
240    0       1    1     0
241    1       1    1     0
242    1       0    1     0
243    0       0    3     0

[244 rows x 4 columns]

In [16]:
for col in ["sex","smoker","day","time"]:
    df[col] = le.fit_transform(df[col])

print(df)

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]