In [45]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

In [46]:
df=sns.load_dataset("tips")

In [47]:
df

     total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
17        16.29   3.71    Male     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
19        20.65   3.35    Male     No   Sat  Dinner     3
20        17.92   4.08    Male     No   Sat  Dinner     2
21        20.29   2.75  Female     No   Sat  Dinner     2
22        15.77   2.23  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82   3.18    Male     No   Sat  Dinner     2
25        17.81   2.34    Male     No   Sat  Dinner     4
26        13.37   2.00    Male     No   Sat  Dinner     2
27        12.69   2.00    Male     No   Sat  Dinner     2
28        21.70   4.30    Male     No   Sat  Dinner     2
29        19.65   3.00  Female     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
31        18.35   2.50    Male     No   Sat  Dinner     4
32        15.06   3.00  Female     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
34        17.78   3.27    Male     No   Sat  Dinner     2
35        24.06   3.60    Male     No   Sat  Dinner     3
36        16.31   2.00    Male     No   Sat  Dinner     3
37        16.93   3.07  Female     No   Sat  Dinner     3
38        18.69   2.31    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
40        16.04   2.24    Male     No   Sat  Dinner     3
41        17.46   2.54    Male     No   Sun  Dinner     2
42        13.94   3.06    Male     No   Sun  Dinner     2
43         9.68   1.32    Male     No   Sun  Dinner     2
44        30.40   5.60    Male     No   Sun  Dinner     4
45        18.29   3.00    Male     No   Sun  Dinner     2
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
49        18.04   3.00    Male     No   Sun  Dinner     2
50        12.54   2.50    Male     No   Sun  Dinner     2
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
53         9.94   1.56    Male     No   Sun  Dinner     2
54        25.56   4.34    Male     No   Sun  Dinner     4
55        19.49   3.51    Male     No   Sun  Dinner     2
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
58        11.24   1.76    Male    Yes   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
61        13.81   2.00    Male    Yes   Sat  Dinner     2
62        11.02   1.98    Male    Yes   Sat  Dinner     2
63        18.29   3.76    Male    Yes   Sat  Dinner     4
64        17.59   2.64    Male     No   Sat  Dinner     3
65        20.08   3.15    Male     No   Sat  Dinner     3
66        16.45   2.47  Female     No   Sat  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
68        20.23   2.01    Male     No   Sat  Dinner     2
69        15.01   2.09    Male    Yes   Sat  Dinner     2
70        12.02   1.97    Male     No   Sat  Dinner     2
71        17.07   3.00  Female     No   Sat  Dinner     3
72        26.86   3.14  Female    Yes   Sat  Dinner     2
73        25.28   5.00  Female    Yes   Sat  Dinner     2
74        14.73   2.20  Female     No   Sat  Dinner     2
75        10.51   1.25    Male     No   Sat  Dinner     2
76        17.92   3.08    Male    Yes   Sat  Dinner     2
77        27.20   4.00    Male     No  Thur   Lunch     4
78        22.76   3.00    Male     No  Thur   Lunch     2
79        17.29   2.71    Male     No  Thur   Lunch     2
80        19.44   3.00    Male    Yes  Thur   Lunch     2
81        16.66   3.40    Male     No  Thur   Lunch     2
82        10.07   1.83  Female     No  Thur   Lunch     1
83        32.68   5.00    Male    Yes  Thur   Lunch     2
84        15.98   2.03    Male     No  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
86        13.03   2.00    Male     No  Thur   Lunch     2
87        18.28   4.00    Male     No  Thur   Lunch     2
88        24.71   5.85    Male     No  Thur   Lunch     2
89        21.16   3.00    Male     No  Thur   Lunch     2
90        28.97   3.00    Male    Yes   Fri  Dinner     2
91        22.49   3.50    Male     No   Fri  Dinner     2
92         5.75   1.00  Female    Yes   Fri  Dinner     2
93        16.32   4.30  Female    Yes   Fri  Dinner     2
94        22.75   3.25  Female     No   Fri  Dinner     2
95        40.17   4.73    Male    Yes   Fri  Dinner     4
96        27.28   4.00    Male    Yes   Fri  Dinner     2
97        12.03   1.50    Male    Yes   Fri  Dinner     2
98        21.01   3.00    Male    Yes   Fri  Dinner     2
99        12.46   1.50    Male     No   Fri  Dinner     2
100       11.35   2.50  Female    Yes   Fri  Dinner     2
101       15.38   3.00  Female    Yes   Fri  Dinner     2
102       44.30   2.50  Female    Yes   Sat  Dinner     3
103       22.42   3.48  Female    Yes   Sat  Dinner     2
104       20.92   4.08  Female     No   Sat  Dinner     2
105       15.36   1.64    Male    Yes   Sat  Dinner     2
106       20.49   4.06    Male    Yes   Sat  Dinner     2
107       25.21   4.29    Male    Yes   Sat  Dinner     2
108       18.24   3.76    Male     No   Sat  Dinner     2
109       14.31   4.00  Female    Yes   Sat  Dinner     2
110       14.00   3.00    Male     No   Sat  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
112       38.07   4.00    Male     No   Sun  Dinner     3
113       23.95   2.55    Male     No   Sun  Dinner     2
114       25.71   4.00  Female     No   Sun  Dinner     3
115       17.31   3.50  Female     No   Sun  Dinner     2
116       29.93   5.07    Male     No   Sun  Dinner     4
117       10.65   1.50  Female     No  Thur   Lunch     2
118       12.43   1.80  Female     No  Thur   Lunch     2
119       24.08   2.92  Female     No  Thur   Lunch     4
120       11.69   2.31    Male     No  Thur   Lunch     2
121       13.42   1.68  Female     No  Thur   Lunch     2
122       14.26   2.50    Male     No  Thur   Lunch     2
123       15.95   2.00    Male     No  Thur   Lunch     2
124       12.48   2.52  Female     No  Thur   Lunch     2
125       29.80   4.20  Female     No  Thur   Lunch     6
126        8.52   1.48    Male     No  Thur   Lunch     2
127       14.52   2.00  Female     No  Thur   Lunch     2
128       11.38   2.00  Female     No  Thur   Lunch     2
129       22.82   2.18    Male     No  Thur   Lunch     3
130       19.08   1.50    Male     No  Thur   Lunch     2
131       20.27   2.83  Female     No  Thur   Lunch     2
132       11.17   1.50  Female     No  Thur   Lunch     2
133       12.26   2.00  Female     No  Thur   Lunch     2
134       18.26   3.25  Female     No  Thur   Lunch     2
135        8.51   1.25  Female     No  Thur   Lunch     2
136       10.33   2.00  Female     No  Thur   Lunch     2
137       14.15   2.00  Female     No  Thur   Lunch     2
138       16.00   2.00    Male    Yes  Thur   Lunch     2
139       13.16   2.75  Female     No  Thur   Lunch     2
140       17.47   3.50  Female     No  Thur   Lunch     2
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
144       16.43   2.30  Female     No  Thur   Lunch     2
145        8.35   1.50  Female     No  Thur   Lunch     2
146       18.64   1.36  Female     No  Thur   Lunch     3
147       11.87   1.63  Female     No  Thur   Lunch     2
148        9.78   1.73    Male     No  Thur   Lunch     2
149        7.51   2.00    Male     No  Thur   Lunch     2
150       14.07   2.50    Male     No   Sun  Dinner     2
151       13.13   2.00    Male     No   Sun  Dinner     2
152       17.26   2.74    Male     No   Sun  Dinner     3
153       24.55   2.00    Male     No   Sun  Dinner     4
154       19.77   2.00    Male     No   Sun  Dinner     4
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
157       25.00   3.75  Female     No   Sun  Dinner     4
158       13.39   2.61  Female     No   Sun  Dinner     2
159       16.49   2.00    Male     No   Sun  Dinner     4
160       21.50   3.50    Male     No   Sun  Dinner     4
161       12.66   2.50    Male     No   Sun  Dinner     2
162       16.21   2.00  Female     No   Sun  Dinner     3
163       13.81   2.00    Male     No   Sun  Dinner     2
164       17.51   3.00  Female    Yes   Sun  Dinner     2
165       24.52   3.48    Male     No   Sun  Dinner     3
166       20.76   2.24    Male     No   Sun  Dinner     2
167       31.71   4.50    Male     No   Sun  Dinner     4
168       10.59   1.61  Female    Yes   Sat  Dinner     2
169       10.63   2.00  Female    Yes   Sat  Dinner     2
170       50.81  10.00    Male    Yes   Sat  Dinner     3
171       15.81   3.16    Male    Yes   Sat  Dinner     2
172        7.25   5.15    Male    Yes   Sun  Dinner     2
173       31.85   3.18    Male    Yes   Sun  Dinner     2
174       16.82   4.00    Male    Yes   Sun  Dinner     2
175       32.90   3.11    Male    Yes   Sun  Dinner     2
176       17.89   2.00    Male    Yes   Sun  Dinner     2
177       14.48   2.00    Male    Yes   Sun  Dinner     2
178        9.60   4.00  Female    Yes   Sun  Dinner     2
179       34.63   3.55    Male    Yes   Sun  Dinner     2
180       34.65   3.68    Male    Yes   Sun  Dinner     4
181       23.33   5.65    Male    Yes   Sun  Dinner     2
182       45.35   3.50    Male    Yes   Sun  Dinner     3
183       23.17   6.50    Male    Yes   Sun  Dinner     4
184       40.55   3.00    Male    Yes   Sun  Dinner     2
185       20.69   5.00    Male     No   Sun  Dinner     5
186       20.90   3.50  Female    Yes   Sun  Dinner     3
187       30.46   2.00    Male    Yes   Sun  Dinner     5
188       18.15   3.50  Female    Yes   Sun  Dinner     3
189       23.10   4.00    Male    Yes   Sun  Dinner     3
190       15.69   1.50    Male    Yes   Sun  Dinner     2
191       19.81   4.19  Female    Yes  Thur   Lunch     2
192       28.44   2.56    Male    Yes  Thur   Lunch     2
193       15.48   2.02    Male    Yes  Thur   Lunch     2
194       16.58   4.00    Male    Yes  Thur   Lunch     2
195        7.56   1.44    Male     No  Thur   Lunch     2
196       10.34   2.00    Male    Yes  Thur   Lunch     2
197       43.11   5.00  Female    Yes  Thur   Lunch     4
198       13.00   2.00  Female    Yes  Thur   Lunch     2
199       13.51   2.00    Male    Yes  Thur   Lunch     2
200       18.71   4.00    Male    Yes  Thur   Lunch     3
201       12.74   2.01  Female    Yes  Thur   Lunch     2
202       13.00   2.00  Female    Yes  Thur   Lunch     2
203       16.40   2.50  Female    Yes  Thur   Lunch     2
204       20.53   4.00    Male    Yes  Thur   Lunch     4
205       16.47   3.23  Female    Yes  Thur   Lunch     3
206       26.59   3.41    Male    Yes   Sat  Dinner     3
207       38.73   3.00    Male    Yes   Sat  Dinner     4
208       24.27   2.03    Male    Yes   Sat  Dinner     2
209       12.76   2.23  Female    Yes   Sat  Dinner     2
210       30.06   2.00    Male    Yes   Sat  Dinner     3
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
213       13.27   2.50  Female    Yes   Sat  Dinner     2
214       28.17   6.50  Female    Yes   Sat  Dinner     3
215       12.90   1.10  Female    Yes   Sat  Dinner     2
216       28.15   3.00    Male    Yes   Sat  Dinner     5
217       11.59   1.50    Male    Yes   Sat  Dinner     2
218        7.74   1.44    Male    Yes   Sat  Dinner     2
219       30.14   3.09  Female    Yes   Sat  Dinner     4
220       12.16   2.20    Male    Yes   Fri   Lunch     2
221       13.42   3.48  Female    Yes   Fri   Lunch     2
222        8.58   1.92    Male    Yes   Fri   Lunch     1
223       15.98   3.00  Female     No   Fri   Lunch     3
224       13.42   1.58    Male    Yes   Fri   Lunch     2
225       16.27   2.50  Female    Yes   Fri   Lunch     2
226       10.09   2.00  Female    Yes   Fri   Lunch     2
227       20.45   3.00    Male     No   Sat  Dinner     4
228       13.28   2.72    Male     No   Sat  Dinner     2
229       22.12   2.88  Female    Yes   Sat  Dinner     2
230       24.01   2.00    Male    Yes   Sat  Dinner     4
231       15.69   3.00    Male    Yes   Sat  Dinner     3
232       11.61   3.39    Male     No   Sat  Dinner     2
233       10.77   1.47    Male     No   Sat  Dinner     2
234       15.53   3.00    Male    Yes   Sat  Dinner     2
235       10.07   1.25    Male     No   Sat  Dinner     2
236       12.60   1.00    Male    Yes   Sat  Dinner     2
237       32.83   1.17    Male    Yes   Sat  Dinner     2
238       35.83   4.67  Female     No   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3
240       27.18   2.00  Female    Yes   Sat  Dinner     2
241       22.67   2.00    Male    Yes   Sat  Dinner     2
242       17.82   1.75    Male     No   Sat  Dinner     2
243       18.78   3.00  Female     No  Thur  Dinner     2

In [49]:
dummydata=pd.get_dummies(df)

In [50]:
dummydata

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,False,True,False,True,False,False,False,True,False,True
1,10.34,1.66,3,True,False,False,True,False,False,False,True,False,True
2,21.01,3.50,3,True,False,False,True,False,False,False,True,False,True
3,23.68,3.31,2,True,False,False,True,False,False,False,True,False,True
4,24.59,3.61,4,False,True,False,True,False,False,False,True,False,True
5,25.29,4.71,4,True,False,False,True,False,False,False,True,False,True
6,8.77,2.00,2,True,False,False,True,False,False,False,True,False,True
7,26.88,3.12,4,True,False,False,True,False,False,False,True,False,True
8,15.04,1.96,2,True,False,False,True,False,False,False,True,False,True
9,14.78,3.23,2,True,False,False,True,False,False,False,True,False,True
10,10.27,1.71,2,True,False,False,True,False,False,False,True,False,True
11,35.26,5.00,4,False,True,False,True,False,False,False,True,False,True
12,15.42,1.57,2,True,False,False,True,False,False,False,True,False,True
13,18.43,3.00,4,True,False,False,True,False,False,False,True,False,True
14,14.83,3.02,2,False,True,False,True,False,False,False,True,False,True
15,21.58,3.92,2,True,False,False,True,False,False,False,True,False,True
16,10.33,1.67,3,False,True,False,True,False,False,False,True,False,True
17,16.29,3.71,3,True,False,False,True,False,False,False,True,False,True
18,16.97,3.50,3,False,True,False,True,False,False,False,True,False,True
19,20.65,3.35,3,True,False,False,True,False,False,True,False,False,True
20,17.92,4.08,2,True,False,False,True,False,False,True,False,False,True
21,20.29,2.75,2,False,True,False,True,False,False,True,False,False,True
22,15.77,2.23,2,False,True,False,True,False,False,True,False,False,True
23,39.42,7.58,4,True,False,False,True,False,False,True,False,False,True
24,19.82,3.18,2,True,False,False,True,False,False,True,False,False,True
25,17.81,2.34,4,True,False,False,True,False,False,True,False,False,True
26,13.37,2.00,2,True,False,False,True,False,False,True,False,False,True
27,12.69,2.00,2,True,False,False,True,False,False,True,False,False,True
28,21.70,4.30,2,True,False,False,True,False,False,True,False,False,True
29,19.65,3.00,2,False,True,False,True,False,False,True,False,False,True
30,9.55,1.45,2,True,False,False,True,False,False,True,False,False,True
31,18.35,2.50,4,True,False,False,True,False,False,True,False,False,True
32,15.06,3.00,2,False,True,False,True,False,False,True,False,False,True
33,20.69,2.45,4,False,True,False,True,False,False,True,False,False,True
34,17.78,3.27,2,True,False,False,True,False,False,True,False,False,True
35,24.06,3.60,3,True,False,False,True,False,False,True,False,False,True
36,16.31,2.00,3,True,False,False,True,False,False,True,False,False,True
37,16.93,3.07,3,False,True,False,True,False,False,True,False,False,True
38,18.69,2.31,3,True,False,False,True,False,False,True,False,False,True
39,31.27,5.00,3,True,False,False,True,False,False,True,False,False,True
40,16.04,2.24,3,True,False,False,True,False,False,True,False,False,True
41,17.46,2.54,2,True,False,False,True,False,False,False,True,False,True
42,13.94,3.06,2,True,False,False,True,False,False,False,True,False,True
43,9.68,1.32,2,True,False,False,True,False,False,False,True,False,True
44,30.40,5.60,4,True,False,False,True,False,False,False,True,False,True
45,18.29,3.00,2,True,False,False,True,False,False,False,True,False,True
46,22.23,5.00,2,True,False,False,True,False,False,False,True,False,True
47,32.40,6.00,4,True,False,False,True,False,False,False,True,False,True
48,28.55,2.05,3,True,False,False,True,False,False,False,True,False,True
49,18.04,3.00,2,True,False,False,True,False,False,False,True,False,True
50,12.54,2.50,2,True,False,False,True,False,False,False,True,False,True
51,10.29,2.60,2,False,True,False,True,False,False,False,True,False,True
52,34.81,5.20,4,False,True,False,True,False,False,False,True,False,True
53,9.94,1.56,2,True,False,False,True,False,False,False,True,False,True
54,25.56,4.34,4,True,False,False,True,False,False,False,True,False,True
55,19.49,3.51,2,True,False,False,True,False,False,False,True,False,True
56,38.01,3.00,4,True,False,True,False,False,False,True,False,False,True
57,26.41,1.50,2,False,True,False,True,False,False,True,False,False,True
58,11.24,1.76,2,True,False,True,False,False,False,True,False,False,True
59,48.27,6.73,4,True,False,False,True,False,False,True,False,False,True
60,20.29,3.21,2,True,False,True,False,False,False,True,False,False,True
61,13.81,2.00,2,True,False,True,False,False,False,True,False,False,True
62,11.02,1.98,2,True,False,True,False,False,False,True,False,False,True
63,18.29,3.76,4,True,False,True,False,False,False,True,False,False,True
64,17.59,2.64,3,True,False,False,True,False,False,True,False,False,True
65,20.08,3.15,3,True,False,False,True,False,False,True,False,False,True
66,16.45,2.47,2,False,True,False,True,False,False,True,False,False,True
67,3.07,1.00,1,False,True,True,False,False,False,True,False,False,True
68,20.23,2.01,2,True,False,False,True,False,False,True,False,False,True
69,15.01,2.09,2,True,False,True,False,False,False,True,False,False,True
70,12.02,1.97,2,True,False,False,True,False,False,True,False,False,True
71,17.07,3.00,3,False,True,False,True,False,False,True,False,False,True
72,26.86,3.14,2,False,True,True,False,False,False,True,False,False,True
73,25.28,5.00,2,False,True,True,False,False,False,True,False,False,True
74,14.73,2.20,2,False,True,False,True,False,False,True,False,False,True
75,10.51,1.25,2,True,False,False,True,False,False,True,False,False,True
76,17.92,3.08,2,True,False,True,False,False,False,True,False,False,True
77,27.20,4.00,4,True,False,False,True,True,False,False,False,True,False
78,22.76,3.00,2,True,False,False,True,True,False,False,False,True,False
79,17.29,2.71,2,True,False,False,True,True,False,False,False,True,False
80,19.44,3.00,2,True,False,True,False,True,False,False,False,True,False
81,16.66,3.40,2,True,False,False,True,True,False,False,False,True,False
82,10.07,1.83,1,False,True,False,True,True,False,False,False,True,False
83,32.68,5.00,2,True,False,True,False,True,False,False,False,True,False
84,15.98,2.03,2,True,False,False,True,True,False,False,False,True,False
85,34.83,5.17,4,False,True,False,True,True,False,False,False,True,False
86,13.03,2.00,2,True,False,False,True,True,False,False,False,True,False
87,18.28,4.00,2,True,False,False,True,True,False,False,False,True,False
88,24.71,5.85,2,True,False,False,True,True,False,False,False,True,False
89,21.16,3.00,2,True,False,False,True,True,False,False,False,True,False
90,28.97,3.00,2,True,False,True,False,False,True,False,False,False,True
91,22.49,3.50,2,True,False,False,True,False,True,False,False,False,True
92,5.75,1.00,2,False,True,True,False,False,True,False,False,False,True
93,16.32,4.30,2,False,True,True,False,False,True,False,False,False,True
94,22.75,3.25,2,False,True,False,True,False,True,False,False,False,True
95,40.17,4.73,4,True,False,True,False,False,True,False,False,False,True
96,27.28,4.00,2,True,False,True,False,False,True,False,False,False,True
97,12.03,1.50,2,True,False,True,False,False,True,False,False,False,True
98,21.01,3.00,2,True,False,True,False,False,True,False,False,False,True
99,12.46,1.50,2,True,False,False,True,False,True,False,False,False,True
100,11.35,2.50,2,False,True,True,False,False,True,False,False,False,True
101,15.38,3.00,2,False,True,True,False,False,True,False,False,False,True
102,44.30,2.50,3,False,True,True,False,False,False,True,False,False,True
103,22.42,3.48,2,False,True,True,False,False,False,True,False,False,True
104,20.92,4.08,2,False,True,False,True,False,False,True,False,False,True
105,15.36,1.64,2,True,False,True,False,False,False,True,False,False,True
106,20.49,4.06,2,True,False,True,False,False,False,True,False,False,True
107,25.21,4.29,2,True,False,True,False,False,False,True,False,False,True
108,18.24,3.76,2,True,False,False,True,False,False,True,False,False,True
109,14.31,4.00,2,False,True,True,False,False,False,True,False,False,True
110,14.00,3.00,2,True,False,False,True,False,False,True,False,False,True
111,7.25,1.00,1,False,True,False,True,False,False,True,False,False,True
112,38.07,4.00,3,True,False,False,True,False,False,False,True,False,True
113,23.95,2.55,2,True,False,False,True,False,False,False,True,False,True
114,25.71,4.00,3,False,True,False,True,False,False,False,True,False,True
115,17.31,3.50,2,False,True,False,True,False,False,False,True,False,True
116,29.93,5.07,4,True,False,False,True,False,False,False,True,False,True
117,10.65,1.50,2,False,True,False,True,True,False,False,False,True,False
118,12.43,1.80,2,False,True,False,True,True,False,False,False,True,False
119,24.08,2.92,4,False,True,False,True,True,False,False,False,True,False
120,11.69,2.31,2,True,False,False,True,True,False,False,False,True,False
121,13.42,1.68,2,False,True,False,True,True,False,False,False,True,False
122,14.26,2.50,2,True,False,False,True,True,False,False,False,True,False
123,15.95,2.00,2,True,False,False,True,True,False,False,False,True,False
124,12.48,2.52,2,False,True,False,True,True,False,False,False,True,False
125,29.80,4.20,6,False,True,False,True,True,False,False,False,True,False
126,8.52,1.48,2,True,False,False,True,True,False,False,False,True,False
127,14.52,2.00,2,False,True,False,True,True,False,False,False,True,False
128,11.38,2.00,2,False,True,False,True,True,False,False,False,True,False
129,22.82,2.18,3,True,False,False,True,True,False,False,False,True,False
130,19.08,1.50,2,True,False,False,True,True,False,False,False,True,False
131,20.27,2.83,2,False,True,False,True,True,False,False,False,True,False
132,11.17,1.50,2,False,True,False,True,True,False,False,False,True,False
133,12.26,2.00,2,False,True,False,True,True,False,False,False,True,False
134,18.26,3.25,2,False,True,False,True,True,False,False,False,True,False
135,8.51,1.25,2,False,True,False,True,True,False,False,False,True,False
136,10.33,2.00,2,False,True,False,True,True,False,False,False,True,False
137,14.15,2.00,2,False,True,False,True,True,False,False,False,True,False
138,16.00,2.00,2,True,False,True,False,True,False,False,False,True,False
139,13.16,2.75,2,False,True,False,True,True,False,False,False,True,False
140,17.47,3.50,2,False,True,False,True,True,False,False,False,True,False
141,34.30,6.70,6,True,False,False,True,True,False,False,False,True,False
142,41.19,5.00,5,True,False,False,True,True,False,False,False,True,False
143,27.05,5.00,6,False,True,False,True,True,False,False,False,True,False
144,16.43,2.30,2,False,True,False,True,True,False,False,False,True,False
145,8.35,1.50,2,False,True,False,True,True,False,False,False,True,False
146,18.64,1.36,3,False,True,False,True,True,False,False,False,True,False
147,11.87,1.63,2,False,True,False,True,True,False,False,False,True,False
148,9.78,1.73,2,True,False,False,True,True,False,False,False,True,False
149,7.51,2.00,2,True,False,False,True,True,False,False,False,True,False
150,14.07,2.50,2,True,False,False,True,False,False,False,True,False,True
151,13.13,2.00,2,True,False,False,True,False,False,False,True,False,True
152,17.26,2.74,3,True,False,False,True,False,False,False,True,False,True
153,24.55,2.00,4,True,False,False,True,False,False,False,True,False,True
154,19.77,2.00,4,True,False,False,True,False,False,False,True,False,True
155,29.85,5.14,5,False,True,False,True,False,False,False,True,False,True
156,48.17,5.00,6,True,False,False,True,False,False,False,True,False,True
157,25.00,3.75,4,False,True,False,True,False,False,False,True,False,True
158,13.39,2.61,2,False,True,False,True,False,False,False,True,False,True
159,16.49,2.00,4,True,False,False,True,False,False,False,True,False,True
160,21.50,3.50,4,True,False,False,True,False,False,False,True,False,True
161,12.66,2.50,2,True,False,False,True,False,False,False,True,False,True
162,16.21,2.00,3,False,True,False,True,False,False,False,True,False,True
163,13.81,2.00,2,True,False,False,True,False,False,False,True,False,True
164,17.51,3.00,2,False,True,True,False,False,False,False,True,False,True
165,24.52,3.48,3,True,False,False,True,False,False,False,True,False,True
166,20.76,2.24,2,True,False,False,True,False,False,False,True,False,True
167,31.71,4.50,4,True,False,False,True,False,False,False,True,False,True
168,10.59,1.61,2,False,True,True,False,False,False,True,False,False,True
169,10.63,2.00,2,False,True,True,False,False,False,True,False,False,True
170,50.81,10.00,3,True,False,True,False,False,False,True,False,False,True
171,15.81,3.16,2,True,False,True,False,False,False,True,False,False,True
172,7.25,5.15,2,True,False,True,False,False,False,False,True,False,True
173,31.85,3.18,2,True,False,True,False,False,False,False,True,False,True
174,16.82,4.00,2,True,False,True,False,False,False,False,True,False,True
175,32.90,3.11,2,True,False,True,False,False,False,False,True,False,True
176,17.89,2.00,2,True,False,True,False,False,False,False,True,False,True
177,14.48,2.00,2,True,False,True,False,False,False,False,True,False,True
178,9.60,4.00,2,False,True,True,False,False,False,False,True,False,True
179,34.63,3.55,2,True,False,True,False,False,False,False,True,False,True
180,34.65,3.68,4,True,False,True,False,False,False,False,True,False,True
181,23.33,5.65,2,True,False,True,False,False,False,False,True,False,True
182,45.35,3.50,3,True,False,True,False,False,False,False,True,False,True
183,23.17,6.50,4,True,False,True,False,False,False,False,True,False,True
184,40.55,3.00,2,True,False,True,False,False,False,False,True,False,True
185,20.69,5.00,5,True,False,False,True,False,False,False,True,False,True
186,20.90,3.50,3,False,True,True,False,False,False,False,True,False,True
187,30.46,2.00,5,True,False,True,False,False,False,False,True,False,True
188,18.15,3.50,3,False,True,True,False,False,False,False,True,False,True
189,23.10,4.00,3,True,False,True,False,False,False,False,True,False,True
190,15.69,1.50,2,True,False,True,False,False,False,False,True,False,True
191,19.81,4.19,2,False,True,True,False,True,False,False,False,True,False
192,28.44,2.56,2,True,False,True,False,True,False,False,False,True,False
193,15.48,2.02,2,True,False,True,False,True,False,False,False,True,False
194,16.58,4.00,2,True,False,True,False,True,False,False,False,True,False
195,7.56,1.44,2,True,False,False,True,True,False,False,False,True,False
196,10.34,2.00,2,True,False,True,False,True,False,False,False,True,False
197,43.11,5.00,4,False,True,True,False,True,False,False,False,True,False
198,13.00,2.00,2,False,True,True,False,True,False,False,False,True,False
199,13.51,2.00,2,True,False,True,False,True,False,False,False,True,False
200,18.71,4.00,3,True,False,True,False,True,False,False,False,True,False
201,12.74,2.01,2,False,True,True,False,True,False,False,False,True,False
202,13.00,2.00,2,False,True,True,False,True,False,False,False,True,False
203,16.40,2.50,2,False,True,True,False,True,False,False,False,True,False
204,20.53,4.00,4,True,False,True,False,True,False,False,False,True,False
205,16.47,3.23,3,False,True,True,False,True,False,False,False,True,False
206,26.59,3.41,3,True,False,True,False,False,False,True,False,False,True
207,38.73,3.00,4,True,False,True,False,False,False,True,False,False,True
208,24.27,2.03,2,True,False,True,False,False,False,True,False,False,True
209,12.76,2.23,2,False,True,True,False,False,False,True,False,False,True
210,30.06,2.00,3,True,False,True,False,False,False,True,False,False,True
211,25.89,5.16,4,True,False,True,False,False,False,True,False,False,True
212,48.33,9.00,4,True,False,False,True,False,False,True,False,False,True
213,13.27,2.50,2,False,True,True,False,False,False,True,False,False,True
214,28.17,6.50,3,False,True,True,False,False,False,True,False,False,True
215,12.90,1.10,2,False,True,True,False,False,False,True,False,False,True
216,28.15,3.00,5,True,False,True,False,False,False,True,False,False,True
217,11.59,1.50,2,True,False,True,False,False,False,True,False,False,True
218,7.74,1.44,2,True,False,True,False,False,False,True,False,False,True
219,30.14,3.09,4,False,True,True,False,False,False,True,False,False,True
220,12.16,2.20,2,True,False,True,False,False,True,False,False,True,False
221,13.42,3.48,2,False,True,True,False,False,True,False,False,True,False
222,8.58,1.92,1,True,False,True,False,False,True,False,False,True,False
223,15.98,3.00,3,False,True,False,True,False,True,False,False,True,False
224,13.42,1.58,2,True,False,True,False,False,True,False,False,True,False
225,16.27,2.50,2,False,True,True,False,False,True,False,False,True,False
226,10.09,2.00,2,False,True,True,False,False,True,False,False,True,False
227,20.45,3.00,4,True,False,False,True,False,False,True,False,False,True
228,13.28,2.72,2,True,False,False,True,False,False,True,False,False,True
229,22.12,2.88,2,False,True,True,False,False,False,True,False,False,True
230,24.01,2.00,4,True,False,True,False,False,False,True,False,False,True
231,15.69,3.00,3,True,False,True,False,False,False,True,False,False,True
232,11.61,3.39,2,True,False,False,True,False,False,True,False,False,True
233,10.77,1.47,2,True,False,False,True,False,False,True,False,False,True
234,15.53,3.00,2,True,False,True,False,False,False,True,False,False,True
235,10.07,1.25,2,True,False,False,True,False,False,True,False,False,True
236,12.60,1.00,2,True,False,True,False,False,False,True,False,False,True
237,32.83,1.17,2,True,False,True,False,False,False,True,False,False,True
238,35.83,4.67,3,False,True,False,True,False,False,True,False,False,True
239,29.03,5.92,3,True,False,False,True,False,False,True,False,False,True
240,27.18,2.00,2,False,True,True,False,False,False,True,False,False,True
241,22.67,2.00,2,True,False,True,False,False,False,True,False,False,True
242,17.82,1.75,2,True,False,False,True,False,False,True,False,False,True
243,18.78,3.00,2,False,True,False,True,True,False,False,False,False,True

In [51]:
onh=OneHotEncoder(sparse_output=False)

In [52]:
onh

OneHotEncoder(sparse_output=False)

In [53]:
oh_enco_arr=onh.fit_transform(df[['sex','smoker','day','time']])

In [24]:
oh_enco_arr

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [54]:
dummydata.keys()

Index(['total_bill', 'tip', 'size', 'sex_Male', 'sex_Female', 'smoker_Yes',
       'smoker_No', 'day_Thur', 'day_Fri', 'day_Sat', 'day_Sun', 'time_Lunch',
       'time_Dinner'],
      dtype='object')

In [55]:
oh_enco_df=pd.DataFrame(oh_enco_arr,columns=['sex_Female',
'sex_Male', 'smoker_No',
 'smoker_Yes', 'day_Fri', 'day_Sat', 'day_Sun', 'day_Thur',
 'time_Dinner', 'time_Lunch'])

In [56]:
oh_enco_df

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
5,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
6,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
7,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
8,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
9,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
11,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
12,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
13,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
14,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
15,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
16,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
17,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
18,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
19,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
20,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
21,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
22,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
23,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
24,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
25,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
26,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
27,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
28,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
29,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
30,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
31,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
32,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
33,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
34,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
35,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
36,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
37,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
38,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
39,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
40,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
41,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
42,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
43,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
44,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
45,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
46,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
47,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
48,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
49,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
50,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
51,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
52,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
53,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
54,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
55,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
56,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
57,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
58,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
59,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
60,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
61,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
62,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
63,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
64,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
65,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
66,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
67,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
68,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
69,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
70,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
71,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
72,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
73,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
74,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
75,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
76,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
77,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
78,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
79,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
80,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
81,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
82,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
83,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
84,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
85,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
86,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
87,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
88,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
89,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
90,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
91,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
92,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
93,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
94,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
95,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
96,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
97,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
98,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
99,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
100,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
101,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
102,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
103,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
104,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
105,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
106,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
107,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
108,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
109,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
110,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
111,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
112,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
113,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
114,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
115,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
116,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
117,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
118,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
119,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
120,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
121,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
122,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
123,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
124,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
125,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
126,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
127,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
128,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
129,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
130,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
131,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
132,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
133,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
134,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
135,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
136,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
137,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
138,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
139,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
140,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
141,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
142,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
143,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
144,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
145,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
146,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
147,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
148,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
149,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
150,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
151,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
152,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
153,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
154,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
155,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
156,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
157,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
158,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
159,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
160,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
161,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
162,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
163,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
164,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
165,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
166,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
167,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
168,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
169,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
170,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
171,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
172,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
173,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
174,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
175,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
176,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
177,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
178,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
179,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
180,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
181,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
182,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
183,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
184,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
185,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
186,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
187,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
188,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
189,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
190,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
191,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
192,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
193,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
194,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
195,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
196,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
197,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
198,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
199,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
200,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
201,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
202,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
203,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
204,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
205,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
206,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
207,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
208,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
209,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
210,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
211,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
212,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
213,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
214,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
215,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
216,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
217,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
218,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
219,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
220,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
221,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
222,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
223,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
224,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
225,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
226,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
227,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
228,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
229,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
230,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
231,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
232,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
233,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
234,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
235,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
236,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
237,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
238,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
243,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [28]:
df=sns.load_dataset("tips")

In [29]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
le=LabelEncoder()

In [32]:
df2=df[["sex","smoker","day","time"]]

In [33]:
le.fit_transform(df2["sex"])

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [34]:
le.fit_transform(df2["smoker"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0])

In [35]:
le.fit_transform(df2["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [36]:
le.fit_transform(df2["time"])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [37]:
df2["day"]=le.fit_transform(df2["day"])

C:\Users\LM\AppData\Local\Temp\ipykernel_28144\1644524140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["day"]=le.fit_transform(df2["day"])

In [38]:
df2["day"]

0      2
1      2
2      2
3      2
4      2
      ..
239    1
240    1
241    1
242    1
243    3
Name: day, Length: 244, dtype: int64

In [41]:
df2=df[["sex","smoker","day","time"]].copy()

for col in df2.columns:
    df2[col] = le.fit_transform(df2[col])

# encoded data show
print(df2.head())

   sex  smoker  day  time
0    0       0    2     0
1    1       0    2     0
2    1       0    2     0
3    1       0    2     0
4    0       0    2     0

In [44]:

for col in ["sex","smoker","day","time"]:
    df[col] = le.fit_transform(df[col])

print(df.head())

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4